#!/usr/bin/env bash
# =============================================================================
#  setup.sh — Ubuntu 24.04 LTS First-Time Hardening & Web Server Setup
#  Target : Fresh Ubuntu 24.04 LTS (bare-metal or VPS)
#  Remote : AnyDesk (installed manually by user, port 7070 kept open)
#  Author : Generated hardening script — review before running
#  Usage  : sudo bash setup.sh
# =============================================================================
set -euo pipefail
IFS=$'\n\t'

# ── Colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'
info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
die()     { echo -e "${RED}[ERROR]${RESET} $*" >&2; exit 1; }

# ── Root check ────────────────────────────────────────────────────────────────
[[ $EUID -eq 0 ]] || die "Run as root:  sudo bash $0"

# =============================================================================
# 0. CONFIGURATION  ← Edit these before running
# =============================================================================
NEW_USERNAME="pixxie"                    # Non-root sudo user to create
SSH_PORT=2222                              # Custom SSH port (NOT 22)
ANYDESK_PORT=7070                          # AnyDesk port (keep open)
TIMEZONE="Asia/Bangkok"
# Allowed SSH source IP/CIDR (empty = allow all — not recommended for prod)
SSH_ALLOWED_IP=""                          # e.g. "203.0.113.10/32"

# Web ports (HTTP/HTTPS)
WEB_HTTP=80
WEB_HTTPS=443

# =============================================================================
# 1. SYSTEM UPDATE
# =============================================================================
section() { echo -e "\n${BOLD}${CYAN}══════════════════════════════════════════${RESET}"; \
            echo -e "${BOLD}${CYAN}  $*${RESET}"; \
            echo -e "${BOLD}${CYAN}══════════════════════════════════════════${RESET}"; }

section "1. System Update"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get full-upgrade -y -qq
apt-get autoremove -y -qq
apt-get autoclean -qq
success "System updated"

# =============================================================================
# 2. TIMEZONE & LOCALE
# =============================================================================
section "2. Timezone & Locale"
timedatectl set-timezone "$TIMEZONE"
timedatectl set-ntp true
success "Timezone set to $TIMEZONE, NTP enabled"

# =============================================================================
# 3. INSTALL ESSENTIAL PACKAGES
# =============================================================================
section "3. Essential Packages"
PACKAGES=(
    ufw fail2ban unattended-upgrades apt-listchanges
    curl wget git vim htop net-tools lsof
    auditd audispd-plugins
    libpam-pwquality
    logwatch
    rkhunter chkrootkit
    lynis
    acl
    apparmor apparmor-utils
    needrestart
    chrony
)
apt-get install -y -qq "${PACKAGES[@]}"
success "Packages installed"

# =============================================================================
# 4. CREATE NON-ROOT SUDO USER
# =============================================================================
section "4. Admin User: $NEW_USERNAME"
if ! id "$NEW_USERNAME" &>/dev/null; then
    adduser --gecos "" --disabled-password "$NEW_USERNAME"
    usermod -aG sudo "$NEW_USERNAME"
    # Force password change on first login
    passwd -e "$NEW_USERNAME"
    info "User $NEW_USERNAME created — set password now:"
    passwd "$NEW_USERNAME"
    success "User $NEW_USERNAME created and added to sudo"
else
    warn "User $NEW_USERNAME already exists — skipping creation"
fi

# =============================================================================
# 5. SSH HARDENING
# =============================================================================
section "5. SSH Hardening (port $SSH_PORT)"
SSHD=/etc/ssh/sshd_config
cp "$SSHD" "${SSHD}.bak.$(date +%F)"

cat > /etc/ssh/sshd_config.d/99-hardening.conf <<EOF
# ── SSH Hardening (generated by setup.sh) ──────────────────────────────────
Port $SSH_PORT
AddressFamily inet

# Authentication
PermitRootLogin no
PasswordAuthentication yes           # Set to 'no' after adding SSH key
PubkeyAuthentication yes
AuthenticationMethods publickey,password
MaxAuthTries 3
MaxSessions 3
LoginGraceTime 30

# Keys & Ciphers (modern only)
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com

# Session & Forwarding
ClientAliveInterval 300
ClientAliveCountMax 2
TCPKeepAlive no
X11Forwarding no
AllowAgentForwarding no
AllowTcpForwarding no
PermitTunnel no

# Banners & Logging
Banner /etc/ssh/banner.txt
LogLevel VERBOSE
PrintLastLog yes

# Restrictions
AllowUsers $NEW_USERNAME
UseDNS no
PermitEmptyPasswords no
IgnoreRhosts yes
HostbasedAuthentication no
EOF

cat > /etc/ssh/banner.txt <<'EOF'
╔══════════════════════════════════════════════════════╗
║  AUTHORIZED ACCESS ONLY — All activity is monitored  ║
║  Unauthorized access will be prosecuted to the       ║
║  fullest extent of the law.                          ║
╚══════════════════════════════════════════════════════╝
EOF

systemctl restart ssh
success "SSH hardened on port $SSH_PORT"

# =============================================================================
# 6. FIREWALL (UFW)
# =============================================================================
section "6. Firewall (UFW)"
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw default deny forward

# SSH (custom port)
if [[ -n "$SSH_ALLOWED_IP" ]]; then
    ufw allow from "$SSH_ALLOWED_IP" to any port "$SSH_PORT" proto tcp comment "SSH restricted"
else
    ufw allow "$SSH_PORT"/tcp comment "SSH"
fi

# Web server
ufw allow "$WEB_HTTP"/tcp   comment "HTTP"
ufw allow "$WEB_HTTPS"/tcp  comment "HTTPS"

# AnyDesk
ufw allow "$ANYDESK_PORT"/tcp  comment "AnyDesk TCP"
ufw allow "$ANYDESK_PORT"/udp  comment "AnyDesk UDP"

# Rate-limit SSH
ufw limit "$SSH_PORT"/tcp comment "SSH rate-limit"

ufw --force enable
ufw status verbose
success "UFW firewall configured"

# =============================================================================
# 7. FAIL2BAN
# =============================================================================
section "7. Fail2Ban"
cat > /etc/fail2ban/jail.d/hardening.conf <<EOF
[DEFAULT]
bantime  = 1h
findtime = 10m
maxretry = 3
banaction = ufw
ignoreip = 127.0.0.1/8 ::1

[sshd]
enabled  = true
port     = $SSH_PORT
logpath  = %(sshd_log)s
backend  = %(sshd_backend)s
maxretry = 3
bantime  = 24h

[sshd-ddos]
enabled  = true
port     = $SSH_PORT
logpath  = %(sshd_log)s
maxretry = 6
findtime = 60
bantime  = 24h

[nginx-http-auth]
enabled = true

[nginx-limit-req]
enabled = true

[nginx-botsearch]
enabled = true

[recidive]
enabled  = true
logpath  = /var/log/fail2ban.log
banaction = ufw
bantime  = 1w
findtime = 1d
maxretry = 3
EOF

systemctl enable fail2ban
systemctl restart fail2ban
success "Fail2Ban configured"

# =============================================================================
# 8. AUTOMATIC SECURITY UPDATES
# =============================================================================
section "8. Unattended Security Upgrades"
cat > /etc/apt/apt.conf.d/50unattended-upgrades <<'EOF'
Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}-security";
    "${distro_id}ESMApps:${distro_codename}-apps-security";
    "${distro_id}ESM:${distro_codename}-infra-security";
};
Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
Unattended-Upgrade::Remove-Unused-Dependencies "true";
Unattended-Upgrade::Automatic-Reboot "false";
Unattended-Upgrade::Automatic-Reboot-Time "03:00";
Unattended-Upgrade::Mail "root";
Unattended-Upgrade::MailReport "on-change";
EOF

cat > /etc/apt/apt.conf.d/20auto-upgrades <<'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::AutocleanInterval "7";
EOF

systemctl enable unattended-upgrades
systemctl restart unattended-upgrades
success "Automatic security updates enabled"

# =============================================================================
# 9. KERNEL HARDENING (sysctl)
# =============================================================================
section "9. Kernel Hardening (sysctl)"
cat > /etc/sysctl.d/99-hardening.conf <<'EOF'
# ── Network: IP Spoofing Protection ─────────────────────────────────────────
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0

# ── ICMP / Redirects ─────────────────────────────────────────────────────────
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.secure_redirects = 0
net.ipv4.conf.default.secure_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv4.icmp_ignore_bogus_error_responses = 1

# ── SYN Flood Protection ─────────────────────────────────────────────────────
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 2048
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 5

# ── TCP Hardening ─────────────────────────────────────────────────────────────
net.ipv4.tcp_timestamps = 0
net.ipv4.tcp_rfc1337 = 1

# ── IPv6 (disable if not needed) ─────────────────────────────────────────────
net.ipv6.conf.all.disable_ipv6 = 0
net.ipv6.conf.all.accept_ra = 0
net.ipv6.conf.default.accept_ra = 0

# ── Logging ───────────────────────────────────────────────────────────────────
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1

# ── Memory / Exec Protection ──────────────────────────────────────────────────
kernel.randomize_va_space = 2
kernel.dmesg_restrict = 1
kernel.kptr_restrict = 2
kernel.sysrq = 0
kernel.core_uses_pid = 1
kernel.pid_max = 65536
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
fs.suid_dumpable = 0

# ── Shared Memory ─────────────────────────────────────────────────────────────
kernel.shm_rmid_forced = 1
EOF

sysctl -p /etc/sysctl.d/99-hardening.conf >/dev/null
success "Kernel hardening applied"

# =============================================================================
# 10. PAM / PASSWORD POLICY
# =============================================================================
section "10. Password Policy (PAM)"
# pwquality settings
cat > /etc/security/pwquality.conf <<'EOF'
minlen = 14
dcredit = -1
ucredit = -1
ocredit = -1
lcredit = -1
maxrepeat = 3
maxsequence = 4
gecoscheck = 1
badwords = password qwerty letmein
EOF

# Account lockout
cat > /etc/security/faillock.conf <<'EOF'
deny = 5
unlock_time = 900
fail_interval = 900
audit
silent
EOF

# Password aging
sed -i 's/^PASS_MAX_DAYS.*/PASS_MAX_DAYS   90/'  /etc/login.defs
sed -i 's/^PASS_MIN_DAYS.*/PASS_MIN_DAYS   1/'   /etc/login.defs
sed -i 's/^PASS_WARN_AGE.*/PASS_WARN_AGE   14/'  /etc/login.defs
success "Password policies set"

# =============================================================================
# 11. DISABLE UNUSED SERVICES & PROTOCOLS
# =============================================================================
section "11. Disable Unused Services"
DISABLE_SERVICES=(
    avahi-daemon cups bluetooth
    whoopsie apport
    telnet rsh-server rlogin
)
for svc in "${DISABLE_SERVICES[@]}"; do
    if systemctl list-units --full -all | grep -q "$svc"; then
        systemctl disable --now "$svc" 2>/dev/null && info "Disabled: $svc" || true
    fi
done

# Disable unused filesystems
cat > /etc/modprobe.d/disable-unused-fs.conf <<'EOF'
install cramfs   /bin/true
install freevxfs /bin/true
install jffs2    /bin/true
install hfs      /bin/true
install hfsplus  /bin/true
install squashfs /bin/true
install udf      /bin/true
install fat      /bin/true
install vfat     /bin/true
install nfs      /bin/true
install nfsv3    /bin/true
install gfs2     /bin/true
EOF

# Disable unused network protocols
cat > /etc/modprobe.d/disable-unused-net.conf <<'EOF'
install dccp    /bin/true
install sctp    /bin/true
install rds     /bin/true
install tipc    /bin/true
install n-hdlc  /bin/true
install ax25    /bin/true
install netrom  /bin/true
install x25     /bin/true
install rose    /bin/true
install decnet  /bin/true
install econet  /bin/true
install af_802154 /bin/true
install ipx     /bin/true
install appletalk /bin/true
install psnap   /bin/true
install p8023   /bin/true
install llc     /bin/true
install p8022   /bin/true
EOF
success "Unused services and protocols disabled"

# =============================================================================
# 12. AUDIT DAEMON
# =============================================================================
section "12. Audit Daemon (auditd)"
cat > /etc/audit/rules.d/hardening.rules <<'EOF'
# Delete all existing rules
-D
# Set buffer size
-b 8192
# Failure mode: 1=log, 2=panic
-f 1

# ── Monitor critical files ───────────────────────────────────────────────────
-w /etc/passwd         -p wa -k identity
-w /etc/group          -p wa -k identity
-w /etc/shadow         -p wa -k identity
-w /etc/sudoers        -p wa -k sudoers
-w /etc/sudoers.d/     -p wa -k sudoers
-w /etc/ssh/sshd_config -p wa -k sshd_config
-w /etc/hosts          -p wa -k hosts
-w /etc/crontab        -p wa -k cron
-w /var/spool/cron/    -p wa -k cron
-w /etc/cron.d/        -p wa -k cron

# ── Privilege escalation ─────────────────────────────────────────────────────
-w /bin/su             -p x  -k priv_esc
-w /usr/bin/sudo       -p x  -k priv_esc
-w /usr/bin/passwd     -p x  -k passwd_change

# ── Network config changes ───────────────────────────────────────────────────
-w /etc/network/       -p wa -k network
-w /etc/ufw/           -p wa -k firewall
-w /etc/iptables/      -p wa -k firewall

# ── Login/logout ─────────────────────────────────────────────────────────────
-w /var/log/faillog    -p wa -k logins
-w /var/log/lastlog    -p wa -k logins
-w /var/run/utmp       -p wa -k session
-w /var/log/wtmp       -p wa -k session
-w /var/log/btmp       -p wa -k session

# ── Kernel modules ───────────────────────────────────────────────────────────
-w /sbin/insmod        -p x  -k modules
-w /sbin/rmmod         -p x  -k modules
-w /sbin/modprobe      -p x  -k modules
-a always,exit -F arch=b64 -S init_module -S delete_module -k modules

# ── System calls: suspicious ─────────────────────────────────────────────────
-a always,exit -F arch=b64 -S ptrace          -k ptrace
-a always,exit -F arch=b64 -S personality     -k unusual_syscall
-a always,exit -F arch=b64 -S unshare         -k namespace

# Make rules immutable (requires reboot to change)
-e 2
EOF

systemctl enable auditd
systemctl restart auditd
success "Audit rules configured"

# =============================================================================
# 13. LOGWATCH — Daily Log Reports
# =============================================================================
section "13. Logwatch"
cat > /etc/logwatch/conf/logwatch.conf <<'EOF'
Output = mail
Format = html
MailTo = root
MailFrom = logwatch@localhost
Range = yesterday
Detail = Med
Service = All
EOF
success "Logwatch configured (daily report to root)"

# =============================================================================
# 14. RKHUNTER — Rootkit Scanner
# =============================================================================
section "14. RKHunter"
rkhunter --update --quiet
rkhunter --propupd --quiet
# Daily cron scan
cat > /etc/cron.daily/rkhunter-scan <<'EOF'
#!/bin/bash
/usr/bin/rkhunter --cronjob --update --quiet
EOF
chmod +x /etc/cron.daily/rkhunter-scan
success "RKHunter initialised"

# =============================================================================
# 15. APPARMOR
# =============================================================================
section "15. AppArmor"
aa-enforce /etc/apparmor.d/* 2>/dev/null || true
systemctl enable apparmor
systemctl start apparmor
success "AppArmor enforced"

# =============================================================================
# 16. SHARED MEMORY HARDENING (/run/shm)
# =============================================================================
section "16. /run/shm Hardening"
if ! grep -q '/run/shm' /etc/fstab; then
    echo 'none /run/shm tmpfs defaults,noexec,nosuid,nodev 0 0' >> /etc/fstab
    mount -o remount /run/shm 2>/dev/null || true
fi
success "/run/shm hardened"

# =============================================================================
# 17. PROCESS ACCOUNTING
# =============================================================================
section "17. Process Accounting"
apt-get install -y -qq acct
systemctl enable acct
systemctl start acct
success "Process accounting enabled"

# =============================================================================
# 18. UMASK HARDENING
# =============================================================================
section "18. Umask Hardening"
sed -i 's/^UMASK.*/UMASK\t\t027/' /etc/login.defs
echo 'umask 027' >> /etc/profile.d/hardening.sh
success "Default umask set to 027"

# =============================================================================
# 19. ANTI-DDOS (UFW rate-limit + sysctl already applied)
#     Additional: iptables SYN/port-scan protection
# =============================================================================
section "19. DDoS / Port-Scan Mitigations"
# iptables rules for new chain (augments UFW)
iptables -N PORT_SCAN 2>/dev/null || iptables -F PORT_SCAN
iptables -A PORT_SCAN -p tcp --tcp-flags SYN,ACK,FIN,RST RST \
    -m limit --limit 1/s --limit-burst 2 -j RETURN
iptables -A PORT_SCAN -j DROP

iptables -N SYN_FLOOD 2>/dev/null || iptables -F SYN_FLOOD
iptables -A SYN_FLOOD -m limit --limit 10/s --limit-burst 20 -j RETURN
iptables -A SYN_FLOOD -j DROP

# Persist iptables rules
apt-get install -y -qq iptables-persistent
netfilter-persistent save
success "DDoS/SYN-flood/port-scan mitigations applied"

# =============================================================================
# 20. NGINX (Web Server) — Basic Hardened Config Skeleton
# =============================================================================
section "20. Nginx Web Server"
apt-get install -y -qq nginx
systemctl enable nginx

cat > /etc/nginx/conf.d/security.conf <<'EOF'
# ── Security Headers ─────────────────────────────────────────────────────────
add_header X-Frame-Options           "SAMEORIGIN"    always;
add_header X-Content-Type-Options    "nosniff"       always;
add_header X-XSS-Protection          "1; mode=block" always;
add_header Referrer-Policy           "strict-origin-when-cross-origin" always;
add_header Permissions-Policy        "geolocation=(), microphone=(), camera=()" always;
add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
add_header Content-Security-Policy   "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'" always;

# ── Hide version ─────────────────────────────────────────────────────────────
server_tokens off;

# ── Buffer overflow protection ───────────────────────────────────────────────
client_body_buffer_size    16k;
client_header_buffer_size  1k;
client_max_body_size       8m;
large_client_header_buffers 4 4k;

# ── Timeout hardening ────────────────────────────────────────────────────────
client_body_timeout   12;
client_header_timeout 12;
keepalive_timeout     15;
send_timeout          10;

# ── Rate limiting zone ───────────────────────────────────────────────────────
limit_req_zone $binary_remote_addr zone=general:10m rate=30r/m;
limit_conn_zone $binary_remote_addr zone=addr:10m;
EOF

# Disable default site
rm -f /etc/nginx/sites-enabled/default
systemctl reload nginx
success "Nginx installed and hardened"

# =============================================================================
# 21. MOTD (Message of the Day)
# =============================================================================
section "21. Hardened MOTD"
cat > /etc/motd <<'EOF'

  ╔══════════════════════════════════════════════════════════════╗
  ║  AUTHORIZED PERSONNEL ONLY                                   ║
  ║  All connections are logged and monitored.                   ║
  ║  Unauthorized access is strictly prohibited.                 ║
  ╚══════════════════════════════════════════════════════════════╝

EOF
# Disable dynamic MOTD scripts
chmod -x /etc/update-motd.d/* 2>/dev/null || true
success "MOTD updated"

# =============================================================================
# 22. SUMMARY
# =============================================================================
section "✅ Setup Complete"
echo -e "${BOLD}${GREEN}"
cat <<SUMMARY
  ┌─────────────────────────────────────────────────────────────┐
  │  HARDENING SUMMARY                                          │
  ├─────────────────────────────────────────────────────────────┤
  │  SSH Port       : $SSH_PORT (not 22)                            │
  │  Admin User     : $NEW_USERNAME                             │
  │  AnyDesk Port   : $ANYDESK_PORT (open in firewall)              │
  │  Web Ports      : 80 (HTTP), 443 (HTTPS)                    │
  │  Firewall       : UFW enabled                               │
  │  Fail2Ban       : Active                                    │
  │  Auto Updates   : Security patches enabled                  │
  │  Kernel         : Hardened via sysctl                       │
  │  Audit          : auditd active + rules loaded              │
  │  Rootkit Scan   : rkhunter daily                            │
  │  AppArmor       : Enforced                                  │
  └─────────────────────────────────────────────────────────────┘
SUMMARY
echo -e "${RESET}"
warn "NEXT STEPS (manual):"
echo "  1. Add your SSH public key:  ssh-copy-id -p $SSH_PORT $NEW_USERNAME@<server-ip>"
echo "  2. Then set PasswordAuthentication no in /etc/ssh/sshd_config.d/99-hardening.conf"
echo "  3. sudo systemctl restart ssh"
echo "  4. Install AnyDesk manually — port $ANYDESK_PORT is already open in firewall"
echo "  5. Install SSL cert:  apt install certbot python3-certbot-nginx"
echo "  6. Run security audit: sudo lynis audit system"
echo ""
warn "Reboot recommended to apply all kernel & module changes:"
echo "  sudo reboot"
